name: eslac
channels: [conda-forge, bioconda, r]
dependencies:
  - r-base=4.3.*
  - r-tidyverse=2.0.*
  - r-data.table=1.15.*
  - r-readxl=1.4.*
  - r-ggrepel=0.9.*
  - r-ggpubr=0.6.*
  - r-optparse=1.7.*
  - r-yaml=2.3.*
  - r-doParallel=1.0.*
  - r-foreach=1.5.*
  - r-testthat=3.2.*
  - bowtie2=2.5.*
  - samtools=1.20
  - pigz
  - coreutils
